version: '3'

services:
  postgres:
    image: postgres:14
    container_name: pg_container
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/14/data
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        
  notification:
    container_name: 'notification_container'
    build:
      context: ../
      dockerfile: Lappka.Notification/Lappka.Notification.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "5010:80"
    depends_on:
      - rabbitmq
  
        
